# Generated by Django 5.1.1 on 2024-10-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('photo_url', models.URLField(max_length=2000, null=True)),
                ('auth_date', models.CharField(max_length=255)),
            ],
        ),
    ]
